FROM registry.access.redhat.com/ubi10/ubi-minimal:10.0

LABEL org.opencontainers.image.description="Docker image for Quarkus native application base on ubi10/ubi-minimal"

WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work

USER 1001
EXPOSE 8080

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]

COPY --chown=1001:root target/*-runner /work/application